DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
    ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(60) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , BIRTH_DATE DATE
    , VERSION INT NOT NULL DEFAULT 0
    , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
    , PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS USERS;

CREATE TABLE USERS (
    ID INT NOT NULL AUTO_INCREMENT
    , FIRST_NAME VARCHAR(40) NOT NULL
    , LAST_NAME VARCHAR(40) NOT NULL
    , POST VARCHAR(10) NOT NULL
    , LOGIN VARCHAR(20)
    , PASSWORD VARCHAR(20) NOT NULL
    , EMPLOYMENT_DATE DATE
    , UNIQUE UQ_USER_1 (FIRST_NAME, LAST_NAME)
);

DROP TABLE IF EXISTS HOLIDAYS;

CREATE TABLE HOLIDAYS (
    ID INT NOT NULL AUTO_INCREMENT
    , DURATION INT(60) NOT NULL DEFAULT 0
    , STATUS VARCHAR(15) NOT NULL
    , DATE_BEGIN DATE
    , USER_ID INT
    , PRIMARY KEY (ID)
    , FOREIGN KEY(USER_ID) REFERENCES USERS(ID) 
);


